### ISSUE TITLE
Diff btw peer and broadcast?

### ISSUE THREAD

**Issue by sirvon** [cine-io/cineio-peer-android#1]
Thanks for your works guys.

Can you talk about the difference technically btw the peer service and the broadcast service?

Thank you once again.

**Comment by jeffreywescott** [comment]
Hi, @sirvon. cine.io Peer is based on [WebRTC](http://www.webrtc.org/). cine.io Broadcast is based on [RTMP](http://en.wikipedia.org/wiki/Real_Time_Messaging_Protocol).

We also have a Peer --> Broadcast gateway if you need it. We hope this helps!

**Comment by trshafer** [comment]
Hello @sirvon,

Good question. There are many differences between peer and broadcast. The main on is the use case. Peer works best for 1 to 1 or say, 5 to 5. But does not work well for 1 to 1,000,000. Broadcast works well for 1 to N but does not work well for real time chat. 

@jeffreywescott commented on some of the reasons, here are some more:

## cine.io [Peer](https://www.cine.io/products/peer)

### Technology Overview
- Designed for real time chat
- Creates direct connection between each connected peer
  - Meaning if you have 5 connections, each person will be sending out the same video stream to all 5 peers simultaneously. You'd need a really fat pipe to support millions of concurrent connections sending out the same stream.
- People can join [rooms](https://github.com/cine-io/peer-js-sdk#rooms)
  - Room access is defined by your application
- People can [identify](https://github.com/cine-io/peer-js-sdk#identifying-a-user) and [call](https://github.com/cine-io/peer-js-sdk#calling) another identity within a project
  - Securely identifying and who each user can call is defined by your application

### Tech Specifics
- Uses [WebRTC](http://en.wikipedia.org/wiki/WebRTC)
  - This uses [vp8](http://en.wikipedia.org/wiki/VP8) as a video codec
  - This uses [vorbis](http://en.wikipedia.org/wiki/Vorbis) as an audio codec
- [Limited support](http://iswebrtcreadyyet.com/) in web browsers
- We scope all rooms to a each project, ie a connected peer on Project "A" joins room "X", under the hood they're really joining "project-A-room-X". It's a little more complex than that, but that's the idea. 
  - Identities are also scoped per project
- Calling identities uses the same functionality as rooms. Our servers know the identities of your connected peers and send a request to join a random room name created by the server.

## cine.io [Broadcast](https://www.cine.io/products/broadcast)

### Technology Overview
- Designed for broadcasting a single stream to many viewers
- Uses a CDN to distribute the stream across multiple machines to reduce load on machines and provide high availability with fault tolerance (is that redundant?)
- Uses streams created securely by your application.
  - This allows for you to handle who has the name and password to each individual stream
- Provides cloud recording functionality

### Tech Specifics
- Uses [RTMP](http://en.wikipedia.org/wiki/Real_Time_Messaging_Protocol) protocol for ingest
- Support for mobile, web, and mobile web through RTMP and [HLS](http://en.wikipedia.org/wiki/HTTP_Live_Streaming)
- Uses [H.264](http://en.wikipedia.org/wiki/H.264/MPEG-4_AVC) as the video codec
- Uses [AAC](http://en.wikipedia.org/wiki/Advanced_Audio_Coding) as the audio codec

## cine.io [WebRTC Broadcast](https://www.cine.io/products/webrtc-broadcast)

### Technology Overview
- This is a bridge between WebRTC and RTMP.
- Takes a vp8/vorbis WebRTC stream and sends it through our broadcast pipeline

### Tech Specifics
- We have machines that act as a peer. Upon recieving a stream we transmux the stream to rtmp and send it through our existing rtmp pipeline. Pretty neat!

**Comment by sirvon** [comment]
Now aside from the technical marvels of the peer to broadcast bridge/gateway.
sorry for being mentally lazy but i know you guys have this on the forefront of your minds, so...

What is the operational/design/use case, end user ramifications of using the bridge/gateway? 
Which i'm assuming is the webrtc broadcast.

@growlsworth thanks for that quick precise infodump better than the website indeed.

**Comment by jeffreywescott** [comment]
Hi, @sirvon. The main use case we've seen for the RTC to RTMP bridge / gateway is to allow quick and easy video broadcasting from the browser (without the need for Flash). Also, since WebRTC also supports desktop / screen-sharing, it's an easy way to do live screencasts / webinars.

I hope this helps!
